/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package buffer_avro_models;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ETMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5729572173958727459L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ETMessage\",\"namespace\":\"buffer_avro_models\",\"fields\":[{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"group_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"custom_headers\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"{}\"},{\"name\":\"transaction_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"partition\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ETMessage> ENCODER =
      new BinaryMessageEncoder<ETMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ETMessage> DECODER =
      new BinaryMessageDecoder<ETMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ETMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ETMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ETMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ETMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ETMessage from a ByteBuffer. */
  public static ETMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String message;
  @Deprecated public java.lang.String message_id;
  @Deprecated public java.lang.String group_id;
  @Deprecated public java.lang.String custom_headers;
  @Deprecated public java.lang.String transaction_id;
  @Deprecated public int partition;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ETMessage() {}

  /**
   * All-args constructor.
   * @param message The new value for message
   * @param message_id The new value for message_id
   * @param group_id The new value for group_id
   * @param custom_headers The new value for custom_headers
   * @param transaction_id The new value for transaction_id
   * @param partition The new value for partition
   */
  public ETMessage(java.lang.String message, java.lang.String message_id, java.lang.String group_id, java.lang.String custom_headers, java.lang.String transaction_id, java.lang.Integer partition) {
    this.message = message;
    this.message_id = message_id;
    this.group_id = group_id;
    this.custom_headers = custom_headers;
    this.transaction_id = transaction_id;
    this.partition = partition;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    case 1: return message_id;
    case 2: return group_id;
    case 3: return custom_headers;
    case 4: return transaction_id;
    case 5: return partition;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.String)value$; break;
    case 1: message_id = (java.lang.String)value$; break;
    case 2: group_id = (java.lang.String)value$; break;
    case 3: custom_headers = (java.lang.String)value$; break;
    case 4: transaction_id = (java.lang.String)value$; break;
    case 5: partition = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'message_id' field.
   * @return The value of the 'message_id' field.
   */
  public java.lang.String getMessageId() {
    return message_id;
  }

  /**
   * Sets the value of the 'message_id' field.
   * @param value the value to set.
   */
  public void setMessageId(java.lang.String value) {
    this.message_id = value;
  }

  /**
   * Gets the value of the 'group_id' field.
   * @return The value of the 'group_id' field.
   */
  public java.lang.String getGroupId() {
    return group_id;
  }

  /**
   * Sets the value of the 'group_id' field.
   * @param value the value to set.
   */
  public void setGroupId(java.lang.String value) {
    this.group_id = value;
  }

  /**
   * Gets the value of the 'custom_headers' field.
   * @return The value of the 'custom_headers' field.
   */
  public java.lang.String getCustomHeaders() {
    return custom_headers;
  }

  /**
   * Sets the value of the 'custom_headers' field.
   * @param value the value to set.
   */
  public void setCustomHeaders(java.lang.String value) {
    this.custom_headers = value;
  }

  /**
   * Gets the value of the 'transaction_id' field.
   * @return The value of the 'transaction_id' field.
   */
  public java.lang.String getTransactionId() {
    return transaction_id;
  }

  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.transaction_id = value;
  }

  /**
   * Gets the value of the 'partition' field.
   * @return The value of the 'partition' field.
   */
  public java.lang.Integer getPartition() {
    return partition;
  }

  /**
   * Sets the value of the 'partition' field.
   * @param value the value to set.
   */
  public void setPartition(java.lang.Integer value) {
    this.partition = value;
  }

  /**
   * Creates a new ETMessage RecordBuilder.
   * @return A new ETMessage RecordBuilder
   */
  public static buffer_avro_models.ETMessage.Builder newBuilder() {
    return new buffer_avro_models.ETMessage.Builder();
  }

  /**
   * Creates a new ETMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ETMessage RecordBuilder
   */
  public static buffer_avro_models.ETMessage.Builder newBuilder(buffer_avro_models.ETMessage.Builder other) {
    return new buffer_avro_models.ETMessage.Builder(other);
  }

  /**
   * Creates a new ETMessage RecordBuilder by copying an existing ETMessage instance.
   * @param other The existing instance to copy.
   * @return A new ETMessage RecordBuilder
   */
  public static buffer_avro_models.ETMessage.Builder newBuilder(buffer_avro_models.ETMessage other) {
    return new buffer_avro_models.ETMessage.Builder(other);
  }

  /**
   * RecordBuilder for ETMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ETMessage>
    implements org.apache.avro.data.RecordBuilder<ETMessage> {

    private java.lang.String message;
    private java.lang.String message_id;
    private java.lang.String group_id;
    private java.lang.String custom_headers;
    private java.lang.String transaction_id;
    private int partition;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(buffer_avro_models.ETMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message_id)) {
        this.message_id = data().deepCopy(fields()[1].schema(), other.message_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.group_id)) {
        this.group_id = data().deepCopy(fields()[2].schema(), other.group_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.custom_headers)) {
        this.custom_headers = data().deepCopy(fields()[3].schema(), other.custom_headers);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[4].schema(), other.transaction_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.partition)) {
        this.partition = data().deepCopy(fields()[5].schema(), other.partition);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ETMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(buffer_avro_models.ETMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message_id)) {
        this.message_id = data().deepCopy(fields()[1].schema(), other.message_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.group_id)) {
        this.group_id = data().deepCopy(fields()[2].schema(), other.group_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.custom_headers)) {
        this.custom_headers = data().deepCopy(fields()[3].schema(), other.custom_headers);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[4].schema(), other.transaction_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.partition)) {
        this.partition = data().deepCopy(fields()[5].schema(), other.partition);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder setMessage(java.lang.String value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'message_id' field.
      * @return The value.
      */
    public java.lang.String getMessageId() {
      return message_id;
    }

    /**
      * Sets the value of the 'message_id' field.
      * @param value The value of 'message_id'.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder setMessageId(java.lang.String value) {
      validate(fields()[1], value);
      this.message_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'message_id' field has been set.
      * @return True if the 'message_id' field has been set, false otherwise.
      */
    public boolean hasMessageId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'message_id' field.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder clearMessageId() {
      message_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'group_id' field.
      * @return The value.
      */
    public java.lang.String getGroupId() {
      return group_id;
    }

    /**
      * Sets the value of the 'group_id' field.
      * @param value The value of 'group_id'.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder setGroupId(java.lang.String value) {
      validate(fields()[2], value);
      this.group_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'group_id' field has been set.
      * @return True if the 'group_id' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'group_id' field.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder clearGroupId() {
      group_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'custom_headers' field.
      * @return The value.
      */
    public java.lang.String getCustomHeaders() {
      return custom_headers;
    }

    /**
      * Sets the value of the 'custom_headers' field.
      * @param value The value of 'custom_headers'.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder setCustomHeaders(java.lang.String value) {
      validate(fields()[3], value);
      this.custom_headers = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'custom_headers' field has been set.
      * @return True if the 'custom_headers' field has been set, false otherwise.
      */
    public boolean hasCustomHeaders() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'custom_headers' field.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder clearCustomHeaders() {
      custom_headers = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'transaction_id' field.
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return transaction_id;
    }

    /**
      * Sets the value of the 'transaction_id' field.
      * @param value The value of 'transaction_id'.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder setTransactionId(java.lang.String value) {
      validate(fields()[4], value);
      this.transaction_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_id' field has been set.
      * @return True if the 'transaction_id' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'transaction_id' field.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'partition' field.
      * @return The value.
      */
    public java.lang.Integer getPartition() {
      return partition;
    }

    /**
      * Sets the value of the 'partition' field.
      * @param value The value of 'partition'.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder setPartition(int value) {
      validate(fields()[5], value);
      this.partition = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'partition' field has been set.
      * @return True if the 'partition' field has been set, false otherwise.
      */
    public boolean hasPartition() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'partition' field.
      * @return This builder.
      */
    public buffer_avro_models.ETMessage.Builder clearPartition() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ETMessage build() {
      try {
        ETMessage record = new ETMessage();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.String) defaultValue(fields()[0]);
        record.message_id = fieldSetFlags()[1] ? this.message_id : (java.lang.String) defaultValue(fields()[1]);
        record.group_id = fieldSetFlags()[2] ? this.group_id : (java.lang.String) defaultValue(fields()[2]);
        record.custom_headers = fieldSetFlags()[3] ? this.custom_headers : (java.lang.String) defaultValue(fields()[3]);
        record.transaction_id = fieldSetFlags()[4] ? this.transaction_id : (java.lang.String) defaultValue(fields()[4]);
        record.partition = fieldSetFlags()[5] ? this.partition : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ETMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<ETMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ETMessage>
    READER$ = (org.apache.avro.io.DatumReader<ETMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
